name: UI Tests

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps chromium

      - name: Run tests
        run: pytest --alluredir=allure-results

      - name: Upload Allure results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Set up Node
        if: always()
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Allure CLI
        if: always()
        run: npm i -g allure-commandline

      - name: Generate Allure report
        if: always()
        run: allure generate allure-results -o allure-report --clean

      - name: Deploy Allure report to gh-pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
